base_dir: './legal-project-data'
targets: 
    - AIHUB-NEWS-filtered-json
    - kowiki-data-json
    - MODU_NEWSPAER_2020_v1.0-filtered-json
    - MODU_NEWSPAER_2021_v1.0-filtered-json
    - MODU_NEWSPAER_2022_v1.0-filtered-json
    - MODU_NEWSPAER_2023_v1.0-filtered-json
    - naver-news
#output_dir: '/data/llmlaw/FIRST_DEDUPLICATION//General_First_Dedup_WO_CODE'
output_dir: './legal-project-data/General_First_Dedup_WO_CODE'

n_dist: 10
n_output: 1
num_expand: 10
sim_threshold: 0.8
n_gram: 6
char_level: false
seed: 1