base_dir: './legal-project-data'
targets: 
    - NON-CASE-LAW

output_dir: './legal-project-data/DOMAIN_First_Dedup_NON_CASE_LAW_kwr_0.75'

n_dist: 500
min_length: 16
n_output: 1
num_expand: 30
sim_threshold: 0.8
n_gram: 16
char_level: false
seed: 1

min_doc_len: 10
max_doc_len: 65192

min_mean_word_len: 3
max_mean_word_len: 10

symbol_to_word_ratio: 0.1

bullet_point_ratio: 0.9
ellipsis_ratio: 0.3

korean_word_ratio: 0.75
is_cluster: false