base_dir: './legal-project-data'
targets: 
    - Case-Law

output_dir: './legal-project-data/DOMAIN_First_Dedup_CASE_LAW_0.9'

n_dist: 500
min_length: 4
n_output: 1
num_expand: 30
sim_threshold: 0.9
n_gram: 4
char_level: false
seed: 1