base_dir: './legal-project-data'
targets: 
    - Domain-Non-Case-Law

output_dir: './legal-project-data/Domain_First_Dedup_NON_CASE_LAW_0.8_10'

n_dist: 500
min_length: 10
n_output: 1
num_expand: 30
sim_threshold: 0.8
n_gram: 10
char_level: false
seed: 1