base_dir: './legal-project-data'
targets: 
    - Case-Law

output_dir: './legal-project-data/DOMAIN_First_Dedup_CASE_LAW_0.8_16'

n_dist: 500
min_length: 16
n_output: 1
num_expand: 30
sim_threshold: 0.8
n_gram: 16
char_level: false
seed: 1