base_dir: './legal-project-data'
targets:
    - Domain_Preprocessed_CASE_LAW

output_dir: './legal-project-data/Domain_SECOND_Dedup_CASE_LAW'

n_dist: 500
min_length: 16
n_output: 1
num_expand: 30
sim_threshold: 0.8
n_gram: 16
char_level: false
seed: 1