base_dir: './legal-project-data'
targets: 
    - Domain-Public_First_Dedup_NON_CASE_LAW_0.8_10

output_dir: './legal-project-data/Domain-Public_Preprocessed_NON_CASE_LAW_SYM_0.3_KWR_0.7'

n_dist: 100
n_output: 1
is_cluster: False
min_doc_len: 50
max_doc_len: 230000
min_mean_word_len: 3
max_mean_word_len: 10
symbol_to_word_ratio: 0.3
bullet_point_ratio: 0.9
ellipsis_ratio:  0.3
korean_word_ratio: 0.7